# Site settings
author: Austin Asbury
title: My Journey as a Developer
header-img: img/home-bg.png
email: acasbury25@aol.com
copyright_name: Austin Asbury
description: > # this means to ignore newlines until "baseurl:"
  Work Smarter, not Harder
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  Azbury

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
